mode: central
fullnameOverride: fedkube-central
clusterName: fedkube-central
clusterLocation: asia-southeast1-b
releaseId: 0d1789ea7d59db851d35dd1376473af11f04b0fe

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:6f2e5d7bdc86a158aa006475ac8d14518b9b69dcb2c3184f968299a16ce57a3a

serviceAccount:
  name: fedkube-central-workload
  gcpServiceAccount: fedkube-central@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  internalLoadBalancerIP: 10.10.0.10
  superlinkAddress: 10.10.0.10:443

elastic:
  enabled: true
  internalLoadBalancerIP: 10.10.0.11
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-central

training:
  enabled: true
  strategies: [fedavg, fedprox]
  rounds: 30
  localEpochs: 5
