mode: central
fullnameOverride: fedkube-central
clusterName: fedkube-central
clusterLocation: asia-southeast1-b
releaseId: 7ebc5a0a8c7d7cd15912ae035566efbfaa4fcd9a

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:3816bd60acb88fffaeacd18c31f1daacebc50b51c4b9f57fdf4e35e7c7da5101

serviceAccount:
  name: fedkube-central-workload
  gcpServiceAccount: fedkube-central@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  internalLoadBalancerIP: 10.10.0.10
  superlinkAddress: 10.10.0.10:443

elastic:
  enabled: true
  internalLoadBalancerIP: 10.10.0.11
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-central

training:
  enabled: false
  strategies: [fedavg, fedprox]
  rounds: 30
  localEpochs: 5
