mode: central
fullnameOverride: fedkube-central
clusterName: fedkube-central
clusterLocation: asia-southeast1-b
releaseId: 0da1b0bccafc9a7531d79c98408a7ab19139d5a3

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:1484beec3ffd34ae61f3648bb6cd78ace3573474301f9e55be46052d40104b9d

serviceAccount:
  name: fedkube-central-workload
  gcpServiceAccount: fedkube-central@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  internalLoadBalancerIP: 10.10.0.10
  superlinkAddress: 10.10.0.10:443

elastic:
  enabled: true
  internalLoadBalancerIP: 10.10.0.11
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-central

training:
  enabled: true
  strategies: [fedavg, fedprox]
  rounds: 30
  localEpochs: 5
