{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore }}
  labels:
    {{- include "fedkube.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterLocation }}
          clusterName: {{ .Values.clusterName }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
            namespace: external-secrets
{{- end }}
