{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fedkube.serviceAccountName" . }}
  labels:
    {{- include "fedkube.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  {{- with .Values.serviceAccount.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: {{ . | quote }}
  {{- end }}
{{- end }}
