apiVersion: batch/v1
kind: Job
metadata:
  name: fedkube-feeder
  namespace: fedkube-ids
  labels:
    app: fedkube-feeder
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: fedkube-feeder
    spec:
      restartPolicy: Never
      containers:
      - name: flow-feeder
        image: fedkube-feeder:latest
        imagePullPolicy: Never
        env:
        - name: INFERENCE_SERVICE_URL
          value: "http://fedkube-inference.fedkube-ids.svc.cluster.local:8000/predict"
        - name: INFERENCE_READINESS_URL
          value: "http://fedkube-inference.fedkube-ids.svc.cluster.local:8000/health/ready"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
