apiVersion: v1
kind: Service
metadata:
  name: fedkube-inference
  namespace: fedkube-ids
spec:
  type: ClusterIP
  selector:
    app: fedkube-inference
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
