{{- if .Values.externalSecrets.enabled }}
{{- if eq .Values.mode "central" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.flower.tlsSecretName }}
  labels:
    {{- include "fedkube.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
  target:
    name: {{ .Values.flower.tlsSecretName }}
  data:
    - secretKey: ca.crt
      remoteRef: {key: {{ .Values.externalSecrets.flowerCaSecretId | quote }}}
    - secretKey: tls.crt
      remoteRef: {key: {{ .Values.externalSecrets.flowerCertSecretId | quote }}}
    - secretKey: tls.key
      remoteRef: {key: {{ .Values.externalSecrets.flowerKeySecretId | quote }}}
---
{{- end }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.flower.caSecretName }}
  labels:
    {{- include "fedkube.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
  target:
    name: {{ .Values.flower.caSecretName }}
  data:
    - secretKey: ca.crt
      remoteRef: {key: {{ .Values.externalSecrets.flowerCaSecretId | quote }}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.elastic.credentialsSecretName }}
  labels:
    {{- include "fedkube.labels" . | nindent 4 }}
  annotations:
    force-sync: {{ .Values.releaseId | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore }}
  target:
    name: {{ .Values.elastic.credentialsSecretName }}
    template:
      data:
        username: filebeat_writer
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef: {key: {{ .Values.externalSecrets.elasticPasswordSecretId | quote }}}
{{- end }}
