mode: edge
fullnameOverride: fedkube-edge-01
clusterName: fedkube-edge-01
clusterLocation: asia-southeast1-b
releaseId: 83e57c68fd41996c7c91f9edd5af3a1e1af391c4

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:4ed1afba8302d595935fd905ed700d6d01040b1fb84e3182e6c47fda86becc7e

serviceAccount:
  name: fedkube-edge-01-workload
  gcpServiceAccount: fedkube-edge-01@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  superlinkAddress: 10.10.0.10:443

training:
  enabled: false

resources:
  clientApp:
    requests: {cpu: 650m, memory: 2800Mi}

elastic:
  enabled: true
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-edge-01
