mode: edge
fullnameOverride: fedkube-edge-01
clusterName: fedkube-edge-01
clusterLocation: asia-southeast1-b
releaseId: 4cd1b00b2ff89afa4c38d60a3b2dbf945d70996c

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:76ea9442e7f36c1c074fae249229d62290bb5d5c27d36b255876472d97e2451a

serviceAccount:
  name: fedkube-edge-01-workload
  gcpServiceAccount: fedkube-edge-01@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  superlinkAddress: 10.10.0.10:443

training:
  enabled: false

resources:
  clientApp:
    requests: {cpu: 650m, memory: 2800Mi}

elastic:
  enabled: true
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-edge-01
