mode: edge
fullnameOverride: fedkube-edge-01
clusterName: fedkube-edge-01
clusterLocation: asia-southeast1-b
releaseId: 04ada4d3a0dc2cf69243be81d7f0105736812d15

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:123cb957628243a5e6e8eccd5a0c13bd71e6c2075035f9fa1d952d413b46fc82

serviceAccount:
  name: fedkube-edge-01-workload
  gcpServiceAccount: fedkube-edge-01@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  superlinkAddress: 10.10.0.10:443

training:
  enabled: false

resources:
  clientApp:
    requests: {cpu: 650m, memory: 2800Mi}

elastic:
  enabled: true
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-edge-01
