mode: edge
fullnameOverride: fedkube-edge-01
clusterName: fedkube-edge-01
clusterLocation: asia-southeast1-b
releaseId: 0d1789ea7d59db851d35dd1376473af11f04b0fe

image:
  repository: hieunguyen595/fedkube-gnn
  digest: sha256:6f2e5d7bdc86a158aa006475ac8d14518b9b69dcb2c3184f968299a16ce57a3a

serviceAccount:
  name: fedkube-edge-01-workload
  gcpServiceAccount: fedkube-edge-01@fedlearning-20260729-hn.iam.gserviceaccount.com

dataset:
  size: 80Gi

flower:
  superlinkAddress: 10.10.0.10:443

training:
  enabled: false

elastic:
  enabled: true
  remoteUrl: https://10.10.0.11:9200
  retentionDays: 7

externalSecrets:
  serviceAccountName: external-secrets-edge-01
