image:
  repository: hieunguyen595/fedkube-gnn
  tag: unset
  digest: sha256:ccc98bfce2845a2bb649aca122c01dee3b8d6e390816dea0fb1e530ab2847ffd
releaseId: ede3b264c422b78b893657c40540316f4157ad50
modelBundle:
  existingClaim: ""
  existingSecret: fedper-model-bundle
inference:
  enabled: false
demoTarget:
  enabled: false
alertRouter:
  enabled: false
evaluation:
  enabled: true
ingress:
  enabled: false
elasticsearch:
  enabled: false
